### ISSUE TITLE
400 Bad Request when running discover mode

### ISSUE THREAD

**Issue by rjh336** [singer-io/tap-google-search-console#37]
Been seeing this 400 error consistently since Feb 15th 2023. I get this error when trying to replicate `performance_report_custom` or `performance_report_date`.

Logs from Stitch
```
2023-02-20 02:18:50,408Z   main - INFO Running tap-google-search-console version 0.1.1 and target-stitch version 3.2.1
2023-02-20 02:18:51,550Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-google-search-console --config /tmp/tap_discover_config.json --discover
2023-02-20 02:18:51,994Z    tap - CRITICAL HTTP-error-code: 400, Error: Bad Request
2023-02-20 02:18:51,995Z    tap - Traceback (most recent call last):
2023-02-20 02:18:51,995Z    tap -   File "tap-env/bin/tap-google-search-console", line 33, in <module>
2023-02-20 02:18:51,995Z    tap -     sys.exit(load_entry_point('tap-google-search-console==0.1.1', 'console_scripts', 'tap-google-search-console')())
2023-02-20 02:18:51,995Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 229, in wrapped
2023-02-20 02:18:51,995Z    tap -     return fnc(*args, **kwargs)
2023-02-20 02:18:51,995Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_google_search_console/__init__.py", line 41, in main
2023-02-20 02:18:51,995Z    tap -     parsed_args.config.get('request_timeout')) as client:
2023-02-20 02:18:51,995Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff/_sync.py", line 94, in retry
2023-02-20 02:18:51,995Z    tap -     ret = target(*args, **kwargs)
2023-02-20 02:18:51,995Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_google_search_console/client.py", line 227, in __enter__
2023-02-20 02:18:51,995Z    tap -     self.get_access_token()
2023-02-20 02:18:51,995Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff/_sync.py", line 94, in retry
2023-02-20 02:18:51,996Z    tap -     ret = target(*args, **kwargs)
2023-02-20 02:18:51,996Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_google_search_console/client.py", line 259, in get_access_token
2023-02-20 02:18:51,996Z    tap -     raise_for_error(response)
2023-02-20 02:18:51,996Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_google_search_console/client.py", line 180, in raise_for_error
2023-02-20 02:18:51,996Z    tap -     raise ex(message) from None
2023-02-20 02:18:51,996Z    tap - tap_google_search_console.client.GoogleBadRequestError: HTTP-error-code: 400, Error: Bad Request
2023-02-20 02:18:52,032Z   main - INFO Tap exited abnormally with status 1
2023-02-20 02:18:52,034Z   main - INFO No tunnel subprocess to tear down
2023-02-20 02:18:52,034Z   main - INFO Exit status is: Discovery failed with code 1 and error message: "HTTP-error-code: 400, Error: Bad Request".
```

cc @Vi6hal @shantanu73 @rdeshmukh15

**Comment by kethan1122** [comment]
Hello @rjh336 

Do you still see this issue?

**Comment by kethan1122** [comment]
Hello @rjh336. Did u get chance to reauthorise your connection ?

**Comment by rjh336** [comment]
@kethan1122 yes

**Comment by kethan1122** [comment]
That's really weird. Can you make sure that you have all the accesses that are mentioned [here](https://www.stitchdata.com/docs/integrations/saas/google-search-console#setup-requirements)
